apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  namespace: nginx-free
  name: nginx-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
  