---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-free
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-free
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
---